[package]
name = "broker"
version = "0.1.0"
authors = ["ogoes <otavio@ogoes.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "=3.3.2"
config = "=0.11.0"
dotenv = "=0.15.0"
env_logger = "=0.8.3"
log = "=0.4.14"
serde = { version = "=1.0.126", features = ["derive"] }
